Post/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.QuestionList, name='home'),
    path('add_question/', views.addquestion, name="add_question"),
    path('search/', views.search, name="search"),
    path('add_comment/<int:question_id>', views.addcomment_ques, name="add_comment_Q"),
    path('edit_comment/<int:question_id>/<int:comment_id>', views.editcomment, name="edit_comment_Q"),
    path('add_comment/<int:question_id>/<int:answer_id>', views.addcomment_ans, name="add_comment_A"),
    path('<int:question_id>', views.Q_detail, name="detail"),
    path('edit/<int:question_id>', views.editquestion, name='edit_question'),
    path('edit_ans/<int:question_id>/<int:answer_id>', views.editanswer, name='edit_answer'),
    path('upvote/<int:question_id>', views.Upvote, name="upvote"),
]

Stackoverflow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Post.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
]

Post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import tree


TagOptions = (('Python','Python'),('django','django'),('C','C'),('Node.js','Node.js'),
           ('excel','excel'),('pandas','pandas'),('linux','linux'),('data structures','data structures'),
           ('sql','sql'),('other','other'))

class question(models.Model):
    Que_text = models.TextField()
    Que_author = models.ForeignKey(User, on_delete= models.CASCADE)
    Que_created_on = models.DateTimeField(auto_now_add=True)
    Upvotes_Que = models.ManyToManyField(User,related_name = 'Qupvotes', null=True, blank=True)
    Views = models.ManyToManyField(User,related_name = 'Qviews', null=True, blank=True)
    tags = models.CharField(max_length=100, choices=TagOptions, default='other')

    def total_upvotes(self):
        return self.Upvotes_Que.count()

    def total_views(self):
        return self.Views.count()

    class Meta:
        ordering = ['-Que_created_on']

    def __str__(self):
        return self.Que_text

class answer(models.Model):
    question = models.ForeignKey(question, related_name= 'answers', on_delete= models.CASCADE)
    Ans_body = models.TextField()
    Ans_author = models.ForeignKey(User, on_delete= models.CASCADE)
    Ans_created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-Ans_created_on']

    def __str__(self):
        return '%s - %s - %s' % (self.Ans_body,self.question.Que_text, self.Ans_author)

class comment(models.Model):
    question = models.ForeignKey(question, related_name= 'comments',on_delete= models.CASCADE, null=True)
    answer = models.ForeignKey(answer,  related_name= 'comments_ans',on_delete= models.CASCADE, null=True)
    comment_text = models.TextField()
    comment_author = models.ForeignKey(User, on_delete= models.CASCADE)
    comment_created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_created_on']

    def __str__(self):
        return '%s - %s' % (self.comment_text, self.comment_author)

Post/forms.py
from django import forms
from . import models

class AddQuestion(forms.ModelForm):
    class Meta:
        model = models.question
        fields = ['Que_text','tags']

class AddAnswer(forms.ModelForm):
    class Meta:
        model = models.answer
        fields = ['Ans_body']

class AddComment_Ques(forms.ModelForm):
    class Meta:
        model = models.comment
        fields = ['comment_text']

class EditComment(forms.ModelForm):
    class Meta:
        model = models.comment
        fields = ['comment_text']

class AddComment_Ans(forms.ModelForm):
    class Meta:
        model = models.comment
        fields = ['comment_text']

class EditForm(forms.ModelForm):
    class Meta:
        model = models.question
        fields = ['Que_text','tags']

Post/views.py
from django.shortcuts import get_object_or_404, render,redirect, HttpResponse
from .models import answer, question, comment
from . import forms
import Post
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import UpdateView
from .forms import EditForm
from django.urls import reverse_lazy

def QuestionList(request):
    questions = question.objects.all()
    context ={
        'question_list': questions,
    }
    return render(request, "home.html", context)

def addquestion(request):
    if request.method=='POST':
        form= forms.AddQuestion(request.POST, request.FILES)
        if form.is_valid():
            instance= form.save(commit=False)
            instance.Que_author = request.user
            instance.save()
            return redirect('home')
    else:
        form= forms.AddQuestion()
    return render(request, 'AddQuestion.html',{'form':form})

def addcomment_ques(request, question_id):
    if request.method=='POST':
        form= forms.AddComment_Ques(request.POST)
        if form.is_valid():
            instance= form.save(commit=False)
            instance.comment_author = request.user
            instance.question = question.objects.get(pk=question_id)
            instance.save()
            return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))
    else:
        form= forms.AddComment_Ques()
    return render(request, 'AddComment.html',{'form':form})

def addcomment_ans(request, answer_id,question_id):
    if request.method=='POST':
        form= forms.AddComment_Ans(request.POST)
        if form.is_valid():
            instance= form.save(commit=False)
            instance.comment_author = request.user
            instance.answer = answer.objects.get(pk=answer_id)
            instance.save()
            return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))
    else:
        form= forms.AddComment_Ans()
    return render(request, 'AddComment_A.html',{'form':form})

def Q_detail(request, question_id):
    obj = get_object_or_404(question, pk=question_id)
    if  request.user.is_authenticated:
        obj.Views.add(request.user)
    # if obj.Views.filter(id=request.user.id).exists():
    #     obj.Views.add(request.user)
        
    is_up = False
    if obj.Upvotes_Que.filter(id=request.user.id).exists():
        is_up = True
        
    if request.method=='POST':
        form= forms.AddAnswer(request.POST, request.FILES)
        if form.is_valid():
            instance= form.save(commit=False)
            instance.Ans_author = request.user
            instance.question = question.objects.get(pk=question_id)
            instance.save()
            return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))
    else:
        form= forms.AddAnswer()
    
    context={
        'obj':obj,
        'form': form,
        'is_up': is_up,
        'total_upvotes':obj.total_upvotes(),
        'total_views':obj.total_views(),
    }
    return render(request, 'detail.html',context)

def Upvote(request, question_id):
    obj = get_object_or_404(question, pk=question_id)
    is_up = False
    if obj.Upvotes_Que.filter(id=request.user.id).exists():
        obj.Upvotes_Que.remove(request.user)
        is_up = False
    else:
        obj.Upvotes_Que.add(request.user)
        is_up = True
    return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))

def search(request):
    query = request.GET['query']
    if len(query)>80:
        questions = []
    else:
        questions = question.objects.filter(tags__icontains=query)
    context ={
        'question_list': questions,
    }
    return render(request, "search.html", context)

def editquestion(request, question_id):
    ques = get_object_or_404(question, pk=question_id)
    
    if request.method=='POST':
        form= forms.EditForm(request.POST,instance=ques)
        
        if form.is_valid():
            instance= form.save(commit=False)
            if instance.Que_author == request.user:
                instance.save()
            return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))
    else:
        form= forms.EditForm(instance=ques)
    return render(request, 'EditQues.html',{'form':form, 'ques':ques})

def editcomment(request,comment_id, question_id):
    comm = get_object_or_404(comment, pk=comment_id)

    if request.method=='POST':
        form= forms.EditComment(request.POST,instance=comm)
        if form.is_valid():
            instance= form.save(commit=False)
            if instance.comment_author == request.user:
                instance.save()
            return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))
    else:
        form= forms.EditComment(instance=comm)
    return render(request, 'EditComment.html',{'form':form, 'comm':comm})

def editanswer(request,answer_id, question_id):
    ans = get_object_or_404(answer, pk=answer_id)

    if request.method=='POST':
        form= forms.AddAnswer(request.POST,instance=ans)
        if form.is_valid():
            instance= form.save(commit=False)
            if instance.Ans_author == request.user:
                instance.save()
            return HttpResponseRedirect(reverse('detail',args=[str(question_id)]))
    else:
        form= forms.AddAnswer(instance=ans)
    return render(request, 'EditAns.html',{'form':form, 'ans':ans})

Post/templates/AddComment.html
{% extends 'base.html' %}

{% block content %}
<style>
    .add-question{
        padding: 35px;
    }
</style>

<div class="add-question">
    <h2>Add your Comments here!</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-secondary">Add Comment</button>
        </form>
        <!-- {{form}}
        <form class="site-form" action="/create/" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_title">Title:</label><input type="text" name="title" class="form-control" maxlength="200" required id="id_title">
            <label for="id_slug">Slug:</label><input type="text" name="slug" class="form-control" maxlength="200" required id="id_slug">
            <label for="id_full_content">Full content:</label><textarea name="full_content" cols="40" rows="10" class="form-control" required id="id_full_content">
    </textarea>
            <label for="id_thumb">Thumb:</label><input type="file" name="thumb" accept="image/*" id="id_thumb">
            <br>
            <input type="submit" value="Create">
        </form> -->
  
</div>

{% endblock %}

Post/templates/AddComment_A.html
{% extends 'base.html' %}

{% block content %}
<style>
    .add-comment{
        padding: 35px;
    }
</style>

<div class="add-comment">
    <h2>Add your Comments for this answer here!</h2>
        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-secondary">Add Comment</button>
        </form> -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea name="comment_text" cols="40" rows="10" required id="id_comment_text" placeholder="Comment"  class="form-control"></textarea><br>
            <button class="btn btn-secondary">Add Comment</button>
        </form>
</div>

{% endblock %}

Post/templates/AddQuestion.html
{% extends 'base.html' %}

{% block content %}
<style>
    .add-question{
        padding: 50px;
        padding-left: 50px;
        padding-right: 10%;
    }
</style>

<div class="add-question">
    <h2>Ask your Question here!</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea name="Que_text" cols="40" rows="10" class="form-control" required id="id_Que_text" placeholder="Question"></textarea>
            <p><label for="id_tags">Tags:</label> <select name="tags" id="id_tags">
                <option value="Python">Python</option>

                <option value="django">django</option>

                <option value="C">C</option>

                <option value="Node.js">Node.js</option>

                <option value="excel">excel</option>

                <option value="pandas">pandas</option>

                <option value="linux">linux</option>

                <option value="data structures">data structures</option>

                <option value="sql">sql</option>

                <option value="other" selected>other</option></select></p><br>
            <button class="btn btn-secondary">Add Question</button>
        </form>
        
        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-secondary">Add Question</button>
        </form>
   -->
</div>

{% endblock %}

Post/templates/EditAns.html
{% extends 'base.html' %}
{% block title %}Edit Answer{% endblock %}
{% block content %}
    
{% if user.is_authenticated %}
<h1>Edit Answer</h1>
<br><br>
<div class="form-group">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-secondary">Edit</button>
</form>
</div>

{% else %}
You are not allowed here! Please go to login.

{% endif %}

{% endblock %}

Post/templates/EditComment.html
{% extends 'base.html' %}
{% block title %}Edit Comment{% endblock %}
{% block content %}
    
{% if user.is_authenticated %}
<h1>Edit Comment</h1>
<br><br>
<div class="form-group">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-secondary">Edit</button>
</form>
</div>

{% else %}
You are not allowed here! Please go to login.

{% endif %}

{% endblock %}

Post/templates/EditQues.html
{% extends 'base.html' %}
{% block title %}Edit Ques{% endblock %}
{% block content %}
    
{% if user.is_authenticated %}
<h1>Edit Question</h1>
<br><br>
<div class="form-group">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-secondary">Update</button>
</form>
</div>

{% else %}
You are not allowed here! Please go to login.

{% endif %}

{% endblock %}

Post/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>StackOverflow</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
            <h4 style="color: white">Stack<span><b>overflow</b></span></h4>
            
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav ml-auto">
                    <form method="GET" action="/search" class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
                        <button class="btn btn-secondary" type="submit">Search</button>
                    </form>
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Questions</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'add_question' %}">Ask Question</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
        
        {% block content %}
   
        {% endblock content %}
    </body>
</html>

Post/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<head>
  <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>   
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function() {
           $( ".accordion" ).accordion({active: false, collapsible: true});
        });
     </script>
     <style>
       .box{
          width: 100%;
          font-size: small;
        }
     </style>
</head>


<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">

      <div class="card-body">
        <h3>{% block title %} {{ obj.Que_text }} {% endblock title %}</h3>
        <small><a href="{% url 'edit_question' obj.pk  %}">Edit</a></small>
        <h6>Tag: {{ obj.tags }}</h6>
        <!-- <h6>Total views: {{ total_views }}</h6> -->
        <small>Views:{{obj.Views.count}} | Comments: {{obj.comments.all.count}} | Answers: {{obj.answers.all.count}}</small><br>
        <small class=" text-muted">{{ obj.Que_author }} | {{ obj.Que_created_on }}</small>
      </div>
      
      {% if user.is_authenticated %}
      <form action="{% url 'upvote' obj.pk %}" method="POST">
        {% csrf_token %}
        {% if is_up %}
          <button type="submit", name="question_id", value="{{ question_id }}", class="btn btn-success">Vote</button>
        {% else %}
          <button type="submit", name="question_id", value="{{ question_id }}", class="btn btn-primary">Vote</button>
        {% endif %} 
        {{ total_upvotes }} Votes
      </form>
      
      {% endif %}
      <hr>
      <br>
      <div class="accordion">
            <!-- <h5>Comments.. <br></h5> -->
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">Comments ({{obj.comments.all.count}})</button>
            <div class="flex">
                {% if user.is_authenticated %}
                  <small><a href="{% url 'add_comment_Q' obj.pk  %}">Add Comments</a></small>
                {% else %}
                  <small>Login to add comments</small><br>
                {% endif %}<br>
                
                {% for j in obj.comments.all %}
                  {{ j.comment_text }}<small> <a href="{% url 'edit_comment_Q' obj.pk j.pk  %}">edit</a></small><br>
                  <small class=" text-muted">{{ j.comment_author}}- {{ j.comment_created_on }}</small> <br>
                  
                {% endfor %}
            </div>
        </div> 


      <br>  
      <h4>Answers..</h4>
      {% if not obj.answers.all %}
          No answers yet..
      {% else %}
          {% for ans in obj.answers.all %}
            <p>{{ ans.Ans_body }} <small> <a href="{% url 'edit_answer' obj.pk ans.pk  %}">Edit</a></small><br>
            <small class=" text-muted">{{ ans.Ans_author}}- {{ ans.Ans_created_on }}</small></p>



            <div class="accordion">
              <p>Comments ({{ans.comments_ans.all.count}})</p>
              <div>
              {% if user.is_authenticated %}
                <small><a href="{% url 'add_comment_A' obj.pk ans.pk  %}">Add ans Comments</a></small>
              {% else %}
                <small>Login to add comments</small><br>
              {% endif %}<br>
              
              {% if not ans.comments_ans.all %}
                  No comments yet..
              {% else %}
                {% for k in ans.comments_ans.all %}
                  <p>{{ k.comment_text }} <small> <a href="{% url 'edit_comment_Q' obj.pk k.pk  %}">edit</a></small><br>
                  <small class=" text-muted">{{ k.comment_author}}- {{ k.comment_created_on }}</small> </p><hr>

                {% endfor %}
              {% endif %}
              </div>
            </div>
            <hr>
          {% endfor %}
          
      {% endif %}
      <hr>

      <h4>Add your Answer here!</h4>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea name="Ans_body" cols="40" rows="10" required id="id_Ans_body" class="form-control" placeholder="Answer"></textarea>
            <br>
            <button class="btn btn-secondary">Add Answer</button>
        </form>
      
    </div>
  </div>
</div>



{% endblock content %}

Post/templates/home.html
{% extends "base.html" %} 

{% block content %}

<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    .centre{
        text-align: left;
        padding-left: 10px;
    }
    
</style>
<br>
<div class="container">
    <h2 class="centre"> All Questions </h2>
    <div class="slider">
        <!-- row-cols-2 row-cols-md-2 g-4 -->
        {% for question in question_list %}
        
        <div class="card">
            <div class="card-body">
                <div class="row" style="position: relative;">
                    <div style="position: absolute;left:10px;">
                        <span style="color: green; font-size: 30px; font-weight:bold;">{{question.Upvotes_Que.count}}</span><br>
                        <small>Votes</small>
                    </div>
                    <div style="padding-left:70px;">
                        <a href="{% url 'detail' question.id %}"><h6 class="card-title">{{question.Que_text|slice:":100" }}</h6></a>
                        <small class="card-subtitle mb-2 text-muted">{{ question.Que_author }} | {{ question.Que_created_on}}</small>
                    </div>
                    <div style="position: absolute;right:10px;"><small>Views:{{question.Views.count}}<br>
                        Comments: {{question.comments.all.count}} |
                        Answers: {{question.answers.all.count}}</small>
                    </div>
                </div>
            </div>
          </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

Post/templates/search.html
{% extends "base.html" %} 

{% block content %}

<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    .centre{
        text-align: left;
        padding-left: 10px;
    }
    
</style>
<br>
<div class="container">
    <h2 class="centre"> Results </h2>
    <div class="slider">
        {% if question_list|length < 1 %}
            <p>No search results</p>
            Your search did not match with any questions.
        {% endif %}
        {% for question in question_list %}
        
        <div class="card">
            <div class="card-body">
                <div class="row" style="position: relative;">
                    <div style="position: absolute;left:10px;">
                        <span style="color: green; font-size: 30px; font-weight:bold;">{{question.Upvotes_Que.count}}</span><br>
                        <small>Votes</small>
                    </div>
                    <div style="padding-left:70px;">
                        <a href="{% url 'detail' question.id %}"><h6 class="card-title">{{question.Que_text|slice:":100" }}</h6></a>
                        <small class="card-subtitle mb-2 text-muted">{{ question.Que_author }} | {{ question.Que_created_on}}</small>
                    </div>
                    <div style="position: absolute;right:10px;"><small>Views:{{question.Views.count}}<br>
                        Comments: {{question.comments.all.count}} |
                        Answers: {{question.answers.all.count}}</small>
                    </div>
                </div>
            </div>
          </div>
        {% endfor %}
    </div>
</div>

{% endblock %}